#!/usr/bin/env python3

import argparse
import os

from pirogue.core.join import Join


if __name__ == "__main__":
    """
    Main process
    """

    # create the top-level parser
    parser = argparse.ArgumentParser()
    parser.add_argument("-v", "--version", help="print the version and exit", action='store_true')
    parser.add_argument('-p', '--pg_service', help='postgres service')

    subparsers = parser.add_subparsers(title='commands', description='pirogue command', dest='command')


    # simple join view
    join_parser = subparsers.add_parser('join', help='create a simple join view')
    join_parser.add_argument('table_a')
    join_parser.add_argument('table_b')

    args = parser.parse_args()

    # print the version and exit
    if args.version:
        print('pirogue version: {}'.format('[DEV]'))
        parser.exit()

    # if no command is passed, print the help and exit
    if not args.command:
        parser.print_help()
        parser.exit()

    exit_val = 0

    if args.pg_service:
        pg_service = args.pg_service
    else:
        pg_service = os.getenv('PGSERVICE')

    if args.command == 'join':
        success = Join(pg_service, args.table_a, args.table_b).create()
        if not success:
            exit_val = 1

    exit(exit_val)
